## Create SQL Environment

In [1]:
import pandas as pd
df=pd.read_csv("/kaggle/input/sales-forecasting/train.csv")
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

## Create SQL environment

In [2]:
import sqlite3
conn=sqlite3.connect("superstore.db")
df.to_sql("sales",conn,index=False,if_exists="replace")

9800

# SQL ANALYSIS QUESTIONS

## Q1. How many total orders are there?

In [3]:
query='''
SELECT COUNT(DISTINCT "Order ID") AS total_orders
FROM sales
'''
pd.read_sql_query(query,conn)

   total_orders
0          4922

## Q2. Total Sales?

In [4]:
query='''
SELECT SUM(Sales) AS total_sales
FROM sales
'''
pd.read_sql_query(query,conn)

    total_sales
0  2.261537e+06

## Q3. Sales by category?

In [5]:
query='''
SELECT Category, SUM(Sales) AS total_sales
FROM sales
GROUP BY Category
ORDER BY total_sales DESC
'''
pd.read_sql_query(query,conn)

          Category  total_sales
0       Technology  827455.8730
1        Furniture  728658.5757
2  Office Supplies  705422.3340

## Q4. Top 5 sub-categories by sales?

In [6]:
query='''
SELECT "Sub-Category", SUM(Sales) AS total_sales
FROM sales
GROUP BY "Sub-Category"
ORDER BY total_sales DESC
LIMIT 5
'''
pd.read_sql_query(query,conn)

  Sub-Category  total_sales
0       Phones   327782.448
1       Chairs   322822.731
2      Storage   219343.392
3       Tables   202810.628
4      Binders   200028.785

## Q5. Sales by region?

In [7]:
query='''
SELECT Region, SUM(Sales) as total_sales
FROM sales
GROUP BY Region
ORDER BY total_sales DESC
'''
pd.read_sql_query(query,conn)

    Region  total_sales
0     West  710219.6845
1     East  669518.7260
2  Central  492646.9132
3    South  389151.4590

## Q6. Average sales per order

In [8]:
query='''
SELECT AVG(Sales) AS avg_sales
FROM sales
'''
pd.read_sql_query(query,conn)

    avg_sales
0  230.769059

## Q7. Top 5 customers by sales?

In [9]:
query='''
SELECT "Customer Name", SUM(Sales) AS total_sales
FROM sales
GROUP BY "Customer Name"
ORDER BY total_sales DESC
LIMIT 5
'''
pd.read_sql_query(query,conn)

   Customer Name  total_sales
0    Sean Miller    25043.050
1   Tamara Chand    19052.218
2   Raymond Buch    15117.339
3   Tom Ashbrook    14595.620
4  Adrian Barton    14473.571

## Q8. Monthly sales trend?

In [10]:
query='''
SELECT
    substr("Order Date",1,7) AS month,
    SUM(Sales) AS monthly_sales
FROM sales
GROUP BY month
ORDER BY month
'''
pd.read_sql_query(query,conn)

       month  monthly_sales
0    01/01/2      1481.8280
1    01/02/2       630.8700
2    01/03/2     10131.1314
3    01/04/2      8254.3560
4    01/05/2      5077.1760
..       ...            ...
360  31/05/2      6390.6970
361  31/07/2      7444.3480
362  31/08/2      5881.1150
363  31/10/2     12847.4620
364  31/12/2      7366.3820

[365 rows x 2 columns]

## Key Insights:

- Sales are concentrated in a few major categories and sub-categories.
- Certain regions contribute significantly more to overall revenue.
- A small group of customers drives a large portion of sales.
- Monthly sales trends suggest seasonal demand patterns.